export const tableData={
     TABLE_ALL_DATA: "TABLE_ALL_DATA",
     SAVE_DATA_SUCCESSFULY: "SUCCESSFULL_SAVE_DATA",
     UPDATE_DATA_SUCCESSFULY:"UPDATE_DATA_SUCCESSFULY",
     DELETE_DATA_SUCCESSFULY:"DELETE_DATA_SUCCESSFULY",
     SHORT_DATA_SUCCESSFULY:"SHORT_DATA_SUCCESSFULY",
     SHEARCH_DATA_SUCCESSFULY:"SHEARCH_DATA_SUCCESSFULY",
     PAGINATION_DATA:"PAGINATION_DATA"
}